### ISSUE TITLE
The problem of image size

### ISSUE THREAD

**Issue by chineselzh** [marcel-goldschen-ohm/ImageViewerQt#1]
hello,thank you for this profile first!
i have some questions ，can you help me?
When I open the program to load the picture, if the image size is smaller than the window size,
I want the picture to be loaded in the original size（not as big as the window）
and I don't know much about the function "fitinview".
Can you improve it?
thank you very much!

**Comment by marcel-goldschen-ohm** [comment]
Sorry, I don't plan to do anything soon with this as I've got many more pressing things to take care of. Feel free to add your own improvements though. Hopefully, this will provide you enough of a starting point ;)
