### ISSUE TITLE
Code to integrate PyQt5 PyQtImageViewer into QT Designer?

### ISSUE THREAD

**Issue by wrishel** [marcel-goldschen-ohm/ImageViewerQt#3]
I am trying to use PyQtImageViewer in an app where the screens are designed using Qt Designer.

As I understand it, the most straightforward way would be to add code to PyQtImageViewer to enable its usage plugin for Designer.  [This Wikipedia article](https://wiki.python.org/moin/PyQt/Using_Python_Custom_Widgets_in_Qt_Designer) has a description of how to do this for Qt 4 and PyQt4. 

I am wondering if anyone has written this code or, better, has written thae same code for PyQt5 and Designer 5?

**Comment by marcel-goldschen-ohm** [comment]
I don't use Qt Designer much, so I'm going to leave this to someone else. If you figure it out and would like to add to this project, that would be great!
Cheers

**Comment by marcel-goldschen-ohm** [comment]
I'm closing this for now, but feel free to reopen.
