### ISSUE TITLE
"QWidget: Must construct a QApplication before a QWidget" Error with PyQt5

### ISSUE THREAD

**Issue by Quasimondo** [marcel-goldschen-ohm/ImageViewerQt#6]
When trying to run the example code within a PyQt5 app I am getting an error message:
"QWidget: Must construct a QApplication before a QWidget"

Looking further into it it is possible that this is caused by me also having PyQt6 installed on my system (which I can't use in this case since I am working on an older app) and the imports inside QtImageViewer are importing the PyQt6 libraries instead of the PyQt5 ones since there is not error triggered and thus the fallback to PyQt5 is not made.

So just in case someone else runs into the same problem - I could fix it by removing the entire block that tries to import PyQt6 libs from QtImageViewer.py.

**Comment by marcel-goldschen-ohm** [comment]
I'd just edit the files for your project to only import PyQt5.
